### PR TITLE
Many fixes

### LINKED ISSUE #12: [Idea] Automatically fix dependencies version number
I think it's better having a fixed dependencies version that will prevent inconsistency when development. To do that we have to add a `.npmrc` file that contains these rules:

```
git-tag-version = false
tag-version-prefix =
save-exact = true
progress = true
```

Or a `.yarnrc` file:

```
save-exact true
save-prefix false
```

These files will fix the dependencies version number during add/install but we have to manually fix the current dependencies version numbers in the `package.json`

### LINKED ISSUE #24: Switch file extension to .postcss
Hi, if we use `.postcss` file extension we can use plugins for a more accurate syntax highlighting.

### PR DESCRIPTION
**Pull request by equinusocio**
This PR will:
- close #12 by fixing and updating dependencies.
- update `.stylelintrc` to allow unkonwn at-rules like `@define-mixin`, `@custom-media`, `@custom-selector`...
- Close #24 by switching to `.postcss` extension.

### CODE REVIEW

**Comment by equinusocio** [comment]
If you use the postcss extension you can use editors plugins to correctly highlight nested rules, plugins and snippets. Normal css syntax does not allow nesting, custom at-riles and other features. Right now i have to force to use the postcss syntax every time i open a css file. 

Eg. If you use postcss “lost” plugin you will have warmings everywhere :)

Since we use postcss + relative plugins i think using the correct file extension can prevent some issue when collaborating.

**Comment by jonathanharrell** [comment]
What editor are you using? I'm using Webstorm, which has an option to choose the css dialect (in my case PostCSS). vscode has https://github.com/MhMadHamster/vscode-postcss-language which works well. I'm not sure about the lost plugin, but most other plugins seems to work well as far as syntax highlighting.

I'm not aware that the postcss file extension is an official extension.

**Comment by equinusocio** [comment]
I’m using vacode with vscode-postcss-language and this plugin automatically associate postcss language to `.postcss` files. Otherwise i have to force it to apply postcss language to each .css files and this is not the correct way because i will lost the normal css language. 

If i don’t set the correct language (postcss) these files have incorrect highlight.

**Comment by jonathanharrell** [comment]
Let's actually use the `.pcss` extension. Looks like Webstorm supports that extension but not `.postcss`. vscode-postcss-language also supports it.

**Comment by equinusocio** [comment]
So we can use .pcss?

**Comment by jonathanharrell** [comment]
Yes, that works.

**Comment by equinusocio** [comment]
Ok i will switch to .pcss 👍🏻

**Comment by equinusocio** [comment]
@jonathanharrell Done! We have to make this change also on v2

**Pull request merged**
