### PR TITLE
Fixes paths on alternatives @import

### PR DESCRIPTION
**Pull request by timhecker**
I've just added `dist/` on import paths

### CODE REVIEW

**Comment by equinusocio** [comment]
@timhecker  Nice! note that `dist/` directory has been removed by [this commit](1b40d28f5b639545bfa8bd2ecb0313988a8d67d4) and will not be available. The only way to use HIQ will be importing hiq.css from `node_modules/hiq/css/hiq.css`

**Comment by timhecker** [comment]
Ok, good, I didn't know :) Thanks

**Comment by equinusocio** [comment]
@jonathanharrell

**Comment by jonathanharrell** [comment]
@equinusocio I still want to allow people to bring in the compiled library from dist so they aren't forced to use through PostCSS. Advanced users would import from `css/`, otherwise import from `dist/`.

**Comment by equinusocio** [comment]
@jonathanharrell Ok, I thought you had taken off the `dist` from NPM also.. :)

**Pull request merged**
